#!/usr/bin/env ruby

#ENGINE_ROOT = File.expand_path('../..', __FILE__)
#ENGINE_PATH = File.expand_path('../../lib/pontiac_webhook/engine', __FILE__)
#
#require 'rails/all'
#require 'rails/engine/commands'

ENGINE_PATH = File.expand_path('../..',  __FILE__)
load File.expand_path('../../spec/dummy/script/rails',  __FILE__)
